AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
  - spec/**/*_spec.rb
  - '*.gemspec'

Metrics/AbcSize:
  Enabled: false
